feat(a11y-tests): allow one url to be tested
If the user wishes to test one specific URL, we help them by allowing
the script to add the entered URL in if it cannot successfully get the
sitemap.xml from the entered URL.

For instance:
* https://yalesites-platform.lndo.site would retrieve the sitemap.xml
  contents
* https://yalesites-platform.lndo.site/homepage would place the homepage
  URL inside of the sitemap.links file

From there, each run in the same way; we are just changing what the
contents of sitemap.links are to target what they wanted.

diff --git a/scripts/retrieveSitemap b/scripts/retrieveSitemap
--- a/scripts/retrieveSitemap
+++ b/scripts/retrieveSitemap
@@ -2,6 +2,11 @@
 
 curl --insecure "$1" 2>/dev/null | xmllint --xpath '//*[local-name()="loc"]/text()' --format - > sitemap.links
 
+if [ $? -ne 0 ]; then
+    echo "Could not retrieve sitemap.xml from url, assuming this is a one-off"
+    echo "$1" > sitemap.links
+fi
+
 if [ ! -f sitemap.links ]; then
     echo "Could not retrieve sitemap.xml"
     exit 1
